language: python
python:
  - "2.7"
#  - "pypy"
#  - "3.3"
#  - "3.4"

os:
  - linux
#  - osx

env:                                                                           
  - PYCOIN_NATIVE=openssl STORJNODE_QUERY_TIMEOUT=3.0

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install meliae
  - python setup.py install

script:
  - pep8 storjnode
  - pep8 examples
  - pep8 tests
  - travis_wait coverage run --source="storjnode" -m unittest --quiet tests
  - coverage report --fail-under=80

after_success:
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false
